[package]
name = "dynamodb"
version = "0.1.0"
edition = "2021"

[dependencies]
askama = "0.12.1"
change-case = "0.2.0"
clap = { version = "4.5.21", features = ["derive"] }
colored = "2.1.0"
serde = { version = "1.0.215", features = ["derive"] }
serde_yaml = "0.9.34"
toml = "0.8.19"

