route_path_config:
  default_route_path: !RoutePath
    name: SignIn
    dir_name: auth
    uri: /sign-in
    path_reg_exp: ^/sign-in$
    children: null
  route_paths:
  - !RoutePath
    name: SignIn
    dir_name: auth
    uri: /sign-in
    path_reg_exp: ^/sign-in$
    children:
    - !RoutePath
      name: SignUp
      dir_name: auth
      uri: /sign-up
      path_reg_exp: ^/sign-up$
      children: null
    - !RoutePath
      name: ForgotPassword
      dir_name: auth
      uri: /forgot-password
      path_reg_exp: ^/forgot-password$
      children:
      - !RoutePath
        name: ResetPassword
        dir_name: auth
        uri: /reset-password
        path_reg_exp: ^/reset-password$
        children: null
  - !RoutePath
    name: VerifyAccount
    dir_name: auth
    uri: /verify-account
    path_reg_exp: ^/verify-account$
    children: null
  - !RoutePath
    name: FetchLoading
    dir_name: auth
    uri: null
    path_reg_exp: null
    children: null
  - !RoutePath
    name: SessionTimeout
    dir_name: auth
    uri: null
    path_reg_exp: null
    children: null
  - !ShellRoute
    name: Main
    dir_name: main
    shell_index: !Enum
    - SampleShell1
    - SampleShell2
    - SampleShell3
    shells:
      SampleShell1: !RoutePath
        name: Sample3
        dir_name: main
        uri: /sample3-url
        path_reg_exp: ^/sample3-url$
        children: null
application_config:
  use_cases:
  - name: signIn
    use_case_type: Query
    return_type:
      name: SignInUser
      path: lib/domain/entity/auth
    dir_name: auth
    args:
    - name: email
      dart_type: null
      nullable: false
      is_final: true
    - name: password
      dart_type: null
      nullable: false
      is_final: true
    exceptions:
    - name: Sample
      description: null
      fields:
      - name: message
        dart_type: null
        nullable: true
        is_final: true
    - name: Sample2
      description: null
      fields:
      - name: message
        dart_type: null
        nullable: true
        is_final: true
  - name: SignOut
    use_case_type: Command
    return_type: null
    dir_name: auth
    args: null
    exceptions:
    - name: Sample
      description: null
      fields:
      - name: message
        dart_type: null
        nullable: true
        is_final: true
    - name: Sample2
      description: null
      fields:
      - name: message
        dart_type: null
        nullable: true
        is_final: true
  - name: ForgotPassword
    use_case_type: Command
    return_type: null
    dir_name: auth
    args:
    - name: email
      dart_type: null
      nullable: false
      is_final: true
    exceptions:
    - name: Sample
      description: null
      fields:
      - name: message
        dart_type: null
        nullable: true
        is_final: true
riverpod_config:
  use_riverpod_generator: false
  providers:
  - name: Sample
    dir_name: auth
    state: null
    auto_dispose: true
    family_type: null
    provider_type: Provider
  - name: Sample2
    dir_name: main
    state:
      name: sample
      path: lib/domain/entity
    auto_dispose: true
    family_type: null
    provider_type: Provider
  - name: Sample2
    dir_name: main
    state:
      name: ClassName
      fields:
      - name: sampleField
        dart_type: null
        nullable: false
        is_final: true
    auto_dispose: true
    family_type: null
    provider_type: Provider
domain_config:
  entities:
  - name: SampleClass
    fields:
    - name: sampleField
      dart_type: null
      nullable: false
      is_final: true
  repositories:
  - name: smple
    exceptions:
    - name: sampleException
      description: これはサンプルの説明
      fields:
      - name: field1
        dart_type: null
        nullable: false
        is_final: true
  services:
  - name: smple
    exceptions:
    - name: sampleException
      description: これはサンプルの説明
      fields:
      - name: field1
        dart_type: null
        nullable: false
        is_final: true
  common_exceptions:
  - name: sampleException
    description: これはサンプルの説明
    fields:
    - name: field1
      dart_type: null
      nullable: false
      is_final: true
